<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kota = [
            ['kode_kota' => 1101, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Simeulue"],
            ['kode_kota' => 1102, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Singkil"],
            ['kode_kota' => 1103, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Selatan"],
            ['kode_kota' => 1104, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Tenggara"],
            ['kode_kota' => 1105, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Timur"],
            ['kode_kota' => 1106, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Tengah"],
            ['kode_kota' => 1107, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Barat"],
            ['kode_kota' => 1108, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Besar"],
            ['kode_kota' => 1109, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Pidie"],
            ['kode_kota' => 1110, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Bireuen"],
            ['kode_kota' => 1111, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Utara"],
            ['kode_kota' => 1112, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Barat Daya"],
            ['kode_kota' => 1113, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Gayo Lues"],
            ['kode_kota' => 1114, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Tamiang"],
            ['kode_kota' => 1115, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Nagan Raya"],
            ['kode_kota' => 1116, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Aceh Jaya"],
            ['kode_kota' => 1117, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Bener Meriah"],
            ['kode_kota' => 1118, 'id_provinsi' => 1, 'nama_kota' => "Kabupaten Pidie Jaya"],
            ['kode_kota' => 1171, 'id_provinsi' => 1, 'nama_kota' => "Kota Banda Aceh"],
            ['kode_kota' => 1172, 'id_provinsi' => 1, 'nama_kota' => "Kota Sabang"],
            ['kode_kota' => 1173, 'id_provinsi' => 1, 'nama_kota' => "Kota Langsa"],
            ['kode_kota' => 1174, 'id_provinsi' => 1, 'nama_kota' => "Kota Lhokseumawe"],
            ['kode_kota' => 1175, 'id_provinsi' => 1, 'nama_kota' => "Kota Subulussalam"],
            ['kode_kota' => 1201, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Nias"],
            ['kode_kota' => 1202, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Mandailing Natal"],
            ['kode_kota' => 1203, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Tapanuli Selatan"],
            ['kode_kota' => 1204, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Tapanuli Tengah"],
            ['kode_kota' => 1205, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Tapanuli Utara"],
            ['kode_kota' => 1206, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Toba Samosir"],
            ['kode_kota' => 1207, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Labuhan Batu"],
            ['kode_kota' => 1208, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Asahan"],
            ['kode_kota' => 1209, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Simalungun"],
            ['kode_kota' => 1210, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Dairi"],
            ['kode_kota' => 1211, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Karo"],
            ['kode_kota' => 1212, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Deli Serdang"],
            ['kode_kota' => 1213, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Langkat"],
            ['kode_kota' => 1214, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Nias Selatan"],
            ['kode_kota' => 1215, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Humbang Hasundutan"],
            ['kode_kota' => 1216, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Pakpak Bharat"],
            ['kode_kota' => 1217, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Samosir"],
            ['kode_kota' => 1218, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Serdang Bedagai"],
            ['kode_kota' => 1219, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Batu Bara"],
            ['kode_kota' => 1220, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Padang Lawas Utara"],
            ['kode_kota' => 1221, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Padang Lawas"],
            ['kode_kota' => 1222, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Labuhan Batu Selatan"],
            ['kode_kota' => 1223, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Labuhan Batu Utara"],
            ['kode_kota' => 1224, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Nias Utara"],
            ['kode_kota' => 1225, 'id_provinsi' => 2, 'nama_kota' => "Kabupaten Nias Barat"],
            ['kode_kota' => 1271, 'id_provinsi' => 2, 'nama_kota' => "Kota Sibolga"],
            ['kode_kota' => 1272, 'id_provinsi' => 2, 'nama_kota' => "Kota Tanjung Balai"],
            ['kode_kota' => 1273, 'id_provinsi' => 2, 'nama_kota' => "Kota Pematang Siantar"],
            ['kode_kota' => 1274, 'id_provinsi' => 2, 'nama_kota' => "Kota Tebing Tinggi"],
            ['kode_kota' => 1275, 'id_provinsi' => 2, 'nama_kota' => "Kota Medan"],
            ['kode_kota' => 1276, 'id_provinsi' => 2, 'nama_kota' => "Kota Binjai"],
            ['kode_kota' => 1277, 'id_provinsi' => 2, 'nama_kota' => "Kota Padangsidimpuan"],
            ['kode_kota' => 1278, 'id_provinsi' => 2, 'nama_kota' => "Kota Gunungsitoli"],
            ['kode_kota' => 1301, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Kepulauan Mentawai"],
            ['kode_kota' => 1302, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Pesisir Selatan"],
            ['kode_kota' => 1303, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Solok"],
            ['kode_kota' => 1304, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Sijunjung"],
            ['kode_kota' => 1305, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Tanah Datar"],
            ['kode_kota' => 1306, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Padang Pariaman"],
            ['kode_kota' => 1307, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Agam"],
            ['kode_kota' => 1308, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Lima Puluh Kota"],
            ['kode_kota' => 1309, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Pasaman"],
            ['kode_kota' => 1310, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Solok Selatan"],
            ['kode_kota' => 1311, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Dharmasraya"],
            ['kode_kota' => 1312, 'id_provinsi' => 3, 'nama_kota' => "Kabupaten Pasaman Barat"],
            ['kode_kota' => 1371, 'id_provinsi' => 3, 'nama_kota' => "Kota Padang"],
            ['kode_kota' => 1372, 'id_provinsi' => 3, 'nama_kota' => "Kota Solok"],
            ['kode_kota' => 1373, 'id_provinsi' => 3, 'nama_kota' => "Kota Sawah Lunto"],
            ['kode_kota' => 1374, 'id_provinsi' => 3, 'nama_kota' => "Kota Padang Panjang"],
            ['kode_kota' => 1375, 'id_provinsi' => 3, 'nama_kota' => "Kota Bukittinggi"],
            ['kode_kota' => 1376, 'id_provinsi' => 3, 'nama_kota' => "Kota Payakumbuh"],
            ['kode_kota' => 1377, 'id_provinsi' => 3, 'nama_kota' => "Kota Pariaman"],
            ['kode_kota' => 1401, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten Kuantan Singingi"],
            ['kode_kota' => 1402, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten Indragiri Hulu"],
            ['kode_kota' => 1403, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten Indragiri Hilir"],
            ['kode_kota' => 1404, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten Pelalawan"],
            ['kode_kota' => 1405, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten S I A K"],
            ['kode_kota' => 1406, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten Kampar"],
            ['kode_kota' => 1407, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten Rokan Hulu"],
            ['kode_kota' => 1408, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten Bengkalis"],
            ['kode_kota' => 1409, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten Rokan Hilir"],
            ['kode_kota' => 1410, 'id_provinsi' => 4, 'nama_kota' => "Kabupaten Kepulauan Meranti"],
            ['kode_kota' => 1471, 'id_provinsi' => 4, 'nama_kota' => "Kota Pekanbaru"],
            ['kode_kota' => 1473, 'id_provinsi' => 4, 'nama_kota' => "Kota D U M A I"],
            ['kode_kota' => 1501, 'id_provinsi' => 5, 'nama_kota' => "Kabupaten Kerinci"],
            ['kode_kota' => 1502, 'id_provinsi' => 5, 'nama_kota' => "Kabupaten Merangin"],
            ['kode_kota' => 1503, 'id_provinsi' => 5, 'nama_kota' => "Kabupaten Sarolangun"],
            ['kode_kota' => 1504, 'id_provinsi' => 5, 'nama_kota' => "Kabupaten Batang Hari"],
            ['kode_kota' => 1505, 'id_provinsi' => 5, 'nama_kota' => "Kabupaten Muaro Jambi"],
            ['kode_kota' => 1506, 'id_provinsi' => 5, 'nama_kota' => "Kabupaten Tanjung Jabung Timur"],
            ['kode_kota' => 1507, 'id_provinsi' => 5, 'nama_kota' => "Kabupaten Tanjung Jabung Barat"],
            ['kode_kota' => 1508, 'id_provinsi' => 5, 'nama_kota' => "Kabupaten Tebo"],
            ['kode_kota' => 1509, 'id_provinsi' => 5, 'nama_kota' => "Kabupaten Bungo"],
            ['kode_kota' => 1571, 'id_provinsi' => 5, 'nama_kota' => "Kota Jambi"],
            ['kode_kota' => 1572, 'id_provinsi' => 5, 'nama_kota' => "Kota Sungai Penuh"],
            ['kode_kota' => 1601, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Ogan Komering Ulu"],
            ['kode_kota' => 1602, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Ogan Komering Ilir"],
            ['kode_kota' => 1603, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Muara Enim"],
            ['kode_kota' => 1604, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Lahat"],
            ['kode_kota' => 1605, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Musi Rawas"],
            ['kode_kota' => 1606, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Musi Banyuasin"],
            ['kode_kota' => 1607, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Banyu Asin"],
            ['kode_kota' => 1608, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Ogan Komering Ulu Selatan"],
            ['kode_kota' => 1609, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Ogan Komering Ulu Timur"],
            ['kode_kota' => 1610, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Ogan Ilir"],
            ['kode_kota' => 1611, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Empat Lawang"],
            ['kode_kota' => 1612, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Penukal Abab Lematang Ilir"],
            ['kode_kota' => 1613, 'id_provinsi' => 6, 'nama_kota' => "Kabupaten Musi Rawas Utara"],
            ['kode_kota' => 1671, 'id_provinsi' => 6, 'nama_kota' => "Kota Palembang"],
            ['kode_kota' => 1672, 'id_provinsi' => 6, 'nama_kota' => "Kota Prabumulih"],
            ['kode_kota' => 1673, 'id_provinsi' => 6, 'nama_kota' => "Kota Pagar Alam"],
            ['kode_kota' => 1674, 'id_provinsi' => 6, 'nama_kota' => "Kota Lubuklinggau"],
            ['kode_kota' => 1701, 'id_provinsi' => 7, 'nama_kota' => "Kabupaten Bengkulu Selatan"],
            ['kode_kota' => 1702, 'id_provinsi' => 7, 'nama_kota' => "Kabupaten Rejang Lebong"],
            ['kode_kota' => 1703, 'id_provinsi' => 7, 'nama_kota' => "Kabupaten Bengkulu Utara"],
            ['kode_kota' => 1704, 'id_provinsi' => 7, 'nama_kota' => "Kabupaten Kaur"],
            ['kode_kota' => 1705, 'id_provinsi' => 7, 'nama_kota' => "Kabupaten Seluma"],
            ['kode_kota' => 1706, 'id_provinsi' => 7, 'nama_kota' => "Kabupaten Mukomuko"],
            ['kode_kota' => 1707, 'id_provinsi' => 7, 'nama_kota' => "Kabupaten Lebong"],
            ['kode_kota' => 1708, 'id_provinsi' => 7, 'nama_kota' => "Kabupaten Kepahiang"],
            ['kode_kota' => 1709, 'id_provinsi' => 7, 'nama_kota' => "Kabupaten Bengkulu Tengah"],
            ['kode_kota' => 1771, 'id_provinsi' => 7, 'nama_kota' => "Kota Bengkulu"],
            ['kode_kota' => 1801, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Lampung Barat"],
            ['kode_kota' => 1802, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Tanggamus"],
            ['kode_kota' => 1803, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Lampung Selatan"],
            ['kode_kota' => 1804, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Lampung Timur"],
            ['kode_kota' => 1805, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Lampung Tengah"],
            ['kode_kota' => 1806, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Lampung Utara"],
            ['kode_kota' => 1807, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Way Kanan"],
            ['kode_kota' => 1808, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Tulangbawang"],
            ['kode_kota' => 1809, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Pesawaran"],
            ['kode_kota' => 1810, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Pringsewu"],
            ['kode_kota' => 1811, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Mesuji"],
            ['kode_kota' => 1812, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Tulang Bawang Barat"],
            ['kode_kota' => 1813, 'id_provinsi' => 8, 'nama_kota' => "Kabupaten Pesisir Barat"],
            ['kode_kota' => 1871, 'id_provinsi' => 8, 'nama_kota' => "Kota Bandar Lampung"],
            ['kode_kota' => 1872, 'id_provinsi' => 8, 'nama_kota' => "Kota Metro"],
            ['kode_kota' => 1901, 'id_provinsi' => 9, 'nama_kota' => "Kabupaten Bangka"],
            ['kode_kota' => 1902, 'id_provinsi' => 9, 'nama_kota' => "Kabupaten Belitung"],
            ['kode_kota' => 1903, 'id_provinsi' => 9, 'nama_kota' => "Kabupaten Bangka Barat"],
            ['kode_kota' => 1904, 'id_provinsi' => 9, 'nama_kota' => "Kabupaten Bangka Tengah"],
            ['kode_kota' => 1905, 'id_provinsi' => 9, 'nama_kota' => "Kabupaten Bangka Selatan"],
            ['kode_kota' => 1906, 'id_provinsi' => 9, 'nama_kota' => "Kabupaten Belitung Timur"],
            ['kode_kota' => 1971, 'id_provinsi' => 9, 'nama_kota' => "Kota Pangkal Pinang"],
            ['kode_kota' => 2101, 'id_provinsi' => 10, 'nama_kota' => "Kabupaten Karimun"],
            ['kode_kota' => 2102, 'id_provinsi' => 10, 'nama_kota' => "Kabupaten Bintan"],
            ['kode_kota' => 2103, 'id_provinsi' => 10, 'nama_kota' => "Kabupaten Natuna"],
            ['kode_kota' => 2104, 'id_provinsi' => 10, 'nama_kota' => "Kabupaten Lingga"],
            ['kode_kota' => 2105, 'id_provinsi' => 10, 'nama_kota' => "Kabupaten Kepulauan Anambas"],
            ['kode_kota' => 2171, 'id_provinsi' => 10, 'nama_kota' => "Kota Batam"],
            ['kode_kota' => 2172, 'id_provinsi' => 10, 'nama_kota' => "Kota Tanjung Pinang"],
            ['kode_kota' => 3101, 'id_provinsi' => 11, 'nama_kota' => "Kabupaten Kepulauan Seribu"],
            ['kode_kota' => 3171, 'id_provinsi' => 11, 'nama_kota' => "Kota Jakarta Selatan"],
            ['kode_kota' => 3172, 'id_provinsi' => 11, 'nama_kota' => "Kota Jakarta Timur"],
            ['kode_kota' => 3173, 'id_provinsi' => 11, 'nama_kota' => "Kota Jakarta Pusat"],
            ['kode_kota' => 3174, 'id_provinsi' => 11, 'nama_kota' => "Kota Jakarta Barat"],
            ['kode_kota' => 3175, 'id_provinsi' => 11, 'nama_kota' => "Kota Jakarta Utara"],
            ['kode_kota' => 3201, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Bogor"],
            ['kode_kota' => 3202, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Sukabumi"],
            ['kode_kota' => 3203, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Cianjur"],
            ['kode_kota' => 3204, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Bandung"],
            ['kode_kota' => 3205, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Garut"],
            ['kode_kota' => 3206, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Tasikmalaya"],
            ['kode_kota' => 3207, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Ciamis"],
            ['kode_kota' => 3208, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Kuningan"],
            ['kode_kota' => 3209, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Cirebon"],
            ['kode_kota' => 3210, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Majalengka"],
            ['kode_kota' => 3211, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Sumedang"],
            ['kode_kota' => 3212, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Indramayu"],
            ['kode_kota' => 3213, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Subang"],
            ['kode_kota' => 3214, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Purwakarta"],
            ['kode_kota' => 3215, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Karawang"],
            ['kode_kota' => 3216, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Bekasi"],
            ['kode_kota' => 3217, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Bandung Barat"],
            ['kode_kota' => 3218, 'id_provinsi' => 12, 'nama_kota' => "Kabupaten Pangandaran"],
            ['kode_kota' => 3271, 'id_provinsi' => 12, 'nama_kota' => "Kota Bogor"],
            ['kode_kota' => 3272, 'id_provinsi' => 12, 'nama_kota' => "Kota Sukabumi"],
            ['kode_kota' => 3273, 'id_provinsi' => 12, 'nama_kota' => "Kota Bandung"],
            ['kode_kota' => 3274, 'id_provinsi' => 12, 'nama_kota' => "Kota Cirebon"],
            ['kode_kota' => 3275, 'id_provinsi' => 12, 'nama_kota' => "Kota Bekasi"],
            ['kode_kota' => 3276, 'id_provinsi' => 12, 'nama_kota' => "Kota Depok"],
            ['kode_kota' => 3277, 'id_provinsi' => 12, 'nama_kota' => "Kota Cimahi"],
            ['kode_kota' => 3278, 'id_provinsi' => 12, 'nama_kota' => "Kota Tasikmalaya"],
            ['kode_kota' => 3279, 'id_provinsi' => 12, 'nama_kota' => "Kota Banjar"],
            ['kode_kota' => 3301, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Cilacap"],
            ['kode_kota' => 3302, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Banyumas"],
            ['kode_kota' => 3303, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Purbalingga"],
            ['kode_kota' => 3304, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Banjarnegara"],
            ['kode_kota' => 3305, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Kebumen"],
            ['kode_kota' => 3306, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Purworejo"],
            ['kode_kota' => 3307, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Wonosobo"],
            ['kode_kota' => 3308, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Magelang"],
            ['kode_kota' => 3309, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Boyolali"],
            ['kode_kota' => 3310, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Klaten"],
            ['kode_kota' => 3311, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Sukoharjo"],
            ['kode_kota' => 3312, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Wonogiri"],
            ['kode_kota' => 3313, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Karanganyar"],
            ['kode_kota' => 3314, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Sragen"],
            ['kode_kota' => 3315, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Grobogan"],
            ['kode_kota' => 3316, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Blora"],
            ['kode_kota' => 3317, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Rembang"],
            ['kode_kota' => 3318, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Pati"],
            ['kode_kota' => 3319, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Kudus"],
            ['kode_kota' => 3320, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Jepara"],
            ['kode_kota' => 3321, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Demak"],
            ['kode_kota' => 3322, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Semarang"],
            ['kode_kota' => 3323, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Temanggung"],
            ['kode_kota' => 3324, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Kendal"],
            ['kode_kota' => 3325, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Batang"],
            ['kode_kota' => 3326, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Pekalongan"],
            ['kode_kota' => 3327, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Pemalang"],
            ['kode_kota' => 3328, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Tegal"],
            ['kode_kota' => 3329, 'id_provinsi' => 13, 'nama_kota' => "Kabupaten Brebes"],
            ['kode_kota' => 3371, 'id_provinsi' => 13, 'nama_kota' => "Kota Magelang"],
            ['kode_kota' => 3372, 'id_provinsi' => 13, 'nama_kota' => "Kota Surakarta"],
            ['kode_kota' => 3373, 'id_provinsi' => 13, 'nama_kota' => "Kota Salatiga"],
            ['kode_kota' => 3374, 'id_provinsi' => 13, 'nama_kota' => "Kota Semarang"],
            ['kode_kota' => 3375, 'id_provinsi' => 13, 'nama_kota' => "Kota Pekalongan"],
            ['kode_kota' => 3376, 'id_provinsi' => 13, 'nama_kota' => "Kota Tegal"],
            ['kode_kota' => 3401, 'id_provinsi' => 14, 'nama_kota' => "Kabupaten Kulon Progo"],
            ['kode_kota' => 3402, 'id_provinsi' => 14, 'nama_kota' => "Kabupaten Bantul"],
            ['kode_kota' => 3403, 'id_provinsi' => 14, 'nama_kota' => "Kabupaten Gunung Kidul"],
            ['kode_kota' => 3404, 'id_provinsi' => 14, 'nama_kota' => "Kabupaten Sleman"],
            ['kode_kota' => 3471, 'id_provinsi' => 14, 'nama_kota' => "Kota Yogyakarta"],
            ['kode_kota' => 3501, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Pacitan"],
            ['kode_kota' => 3502, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Ponorogo"],
            ['kode_kota' => 3503, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Trenggalek"],
            ['kode_kota' => 3504, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Tulungagung"],
            ['kode_kota' => 3505, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Blitar"],
            ['kode_kota' => 3506, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Kediri"],
            ['kode_kota' => 3507, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Malang"],
            ['kode_kota' => 3508, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Lumajang"],
            ['kode_kota' => 3509, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Jember"],
            ['kode_kota' => 3510, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Banyuwangi"],
            ['kode_kota' => 3511, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Bondowoso"],
            ['kode_kota' => 3512, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Situbondo"],
            ['kode_kota' => 3513, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Probolinggo"],
            ['kode_kota' => 3514, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Pasuruan"],
            ['kode_kota' => 3515, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Sidoarjo"],
            ['kode_kota' => 3516, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Mojokerto"],
            ['kode_kota' => 3517, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Jombang"],
            ['kode_kota' => 3518, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Nganjuk"],
            ['kode_kota' => 3519, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Madiun"],
            ['kode_kota' => 3520, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Magetan"],
            ['kode_kota' => 3521, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Ngawi"],
            ['kode_kota' => 3522, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Bojonegoro"],
            ['kode_kota' => 3523, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Tuban"],
            ['kode_kota' => 3524, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Lamongan"],
            ['kode_kota' => 3525, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Gresik"],
            ['kode_kota' => 3526, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Bangkalan"],
            ['kode_kota' => 3527, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Sampang"],
            ['kode_kota' => 3528, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Pamekasan"],
            ['kode_kota' => 3529, 'id_provinsi' => 15, 'nama_kota' => "Kabupaten Sumenep"],
            ['kode_kota' => 3571, 'id_provinsi' => 15, 'nama_kota' => "Kota Kediri"],
            ['kode_kota' => 3572, 'id_provinsi' => 15, 'nama_kota' => "Kota Blitar"],
            ['kode_kota' => 3573, 'id_provinsi' => 15, 'nama_kota' => "Kota Malang"],
            ['kode_kota' => 3574, 'id_provinsi' => 15, 'nama_kota' => "Kota Probolinggo"],
            ['kode_kota' => 3575, 'id_provinsi' => 15, 'nama_kota' => "Kota Pasuruan"],
            ['kode_kota' => 3576, 'id_provinsi' => 15, 'nama_kota' => "Kota Mojokerto"],
            ['kode_kota' => 3577, 'id_provinsi' => 15, 'nama_kota' => "Kota Madiun"],
            ['kode_kota' => 3578, 'id_provinsi' => 15, 'nama_kota' => "Kota Surabaya"],
            ['kode_kota' => 3579, 'id_provinsi' => 15, 'nama_kota' => "Kota Batu"],
            ['kode_kota' => 3601, 'id_provinsi' => 16, 'nama_kota' => "Kabupaten Pandeglang"],
            ['kode_kota' => 3602, 'id_provinsi' => 16, 'nama_kota' => "Kabupaten Lebak"],
            ['kode_kota' => 3603, 'id_provinsi' => 16, 'nama_kota' => "Kabupaten Tangerang"],
            ['kode_kota' => 3604, 'id_provinsi' => 16, 'nama_kota' => "Kabupaten Serang"],
            ['kode_kota' => 3671, 'id_provinsi' => 16, 'nama_kota' => "Kota Tangerang"],
            ['kode_kota' => 3672, 'id_provinsi' => 16, 'nama_kota' => "Kota Cilegon"],
            ['kode_kota' => 3673, 'id_provinsi' => 16, 'nama_kota' => "Kota Serang"],
            ['kode_kota' => 3674, 'id_provinsi' => 16, 'nama_kota' => "Kota Tangerang Selatan"],
            ['kode_kota' => 5101, 'id_provinsi' => 17, 'nama_kota' => "Kabupaten Jembrana"],
            ['kode_kota' => 5102, 'id_provinsi' => 17, 'nama_kota' => "Kabupaten Tabanan"],
            ['kode_kota' => 5103, 'id_provinsi' => 17, 'nama_kota' => "Kabupaten Badung"],
            ['kode_kota' => 5104, 'id_provinsi' => 17, 'nama_kota' => "Kabupaten Gianyar"],
            ['kode_kota' => 5105, 'id_provinsi' => 17, 'nama_kota' => "Kabupaten Klungkung"],
            ['kode_kota' => 5106, 'id_provinsi' => 17, 'nama_kota' => "Kabupaten Bangli"],
            ['kode_kota' => 5107, 'id_provinsi' => 17, 'nama_kota' => "Kabupaten Karang Asem"],
            ['kode_kota' => 5108, 'id_provinsi' => 17, 'nama_kota' => "Kabupaten Buleleng"],
            ['kode_kota' => 5171, 'id_provinsi' => 17, 'nama_kota' => "Kota Denpasar"],
            ['kode_kota' => 5201, 'id_provinsi' => 18, 'nama_kota' => "Kabupaten Lombok Barat"],
            ['kode_kota' => 5202, 'id_provinsi' => 18, 'nama_kota' => "Kabupaten Lombok Tengah"],
            ['kode_kota' => 5203, 'id_provinsi' => 18, 'nama_kota' => "Kabupaten Lombok Timur"],
            ['kode_kota' => 5204, 'id_provinsi' => 18, 'nama_kota' => "Kabupaten Sumbawa"],
            ['kode_kota' => 5205, 'id_provinsi' => 18, 'nama_kota' => "Kabupaten Dompu"],
            ['kode_kota' => 5206, 'id_provinsi' => 18, 'nama_kota' => "Kabupaten Bima"],
            ['kode_kota' => 5207, 'id_provinsi' => 18, 'nama_kota' => "Kabupaten Sumbawa Barat"],
            ['kode_kota' => 5208, 'id_provinsi' => 18, 'nama_kota' => "Kabupaten Lombok Utara"],
            ['kode_kota' => 5271, 'id_provinsi' => 18, 'nama_kota' => "Kota Mataram"],
            ['kode_kota' => 5272, 'id_provinsi' => 18, 'nama_kota' => "Kota Bima"],
            ['kode_kota' => 5301, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Sumba Barat"],
            ['kode_kota' => 5302, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Sumba Timur"],
            ['kode_kota' => 5303, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Kupang"],
            ['kode_kota' => 5304, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Timor Tengah Selatan"],
            ['kode_kota' => 5305, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Timor Tengah Utara"],
            ['kode_kota' => 5306, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Belu"],
            ['kode_kota' => 5307, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Alor"],
            ['kode_kota' => 5308, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Lembata"],
            ['kode_kota' => 5309, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Flores Timur"],
            ['kode_kota' => 5310, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Sikka"],
            ['kode_kota' => 5311, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Ende"],
            ['kode_kota' => 5312, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Ngada"],
            ['kode_kota' => 5313, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Manggarai"],
            ['kode_kota' => 5314, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Rote Ndao"],
            ['kode_kota' => 5315, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Manggarai Barat"],
            ['kode_kota' => 5316, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Sumba Tengah"],
            ['kode_kota' => 5317, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Sumba Barat Daya"],
            ['kode_kota' => 5318, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Nagekeo"],
            ['kode_kota' => 5319, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Manggarai Timur"],
            ['kode_kota' => 5320, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Sabu Raijua"],
            ['kode_kota' => 5321, 'id_provinsi' => 19, 'nama_kota' => "Kabupaten Malaka"],
            ['kode_kota' => 5371, 'id_provinsi' => 19, 'nama_kota' => "Kota Kupang"],
            ['kode_kota' => 6101, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Sambas"],
            ['kode_kota' => 6102, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Bengkayang"],
            ['kode_kota' => 6103, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Landak"],
            ['kode_kota' => 6104, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Mempawah"],
            ['kode_kota' => 6105, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Sanggau"],
            ['kode_kota' => 6106, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Ketapang"],
            ['kode_kota' => 6107, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Sintang"],
            ['kode_kota' => 6108, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Kapuas Hulu"],
            ['kode_kota' => 6109, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Sekadau"],
            ['kode_kota' => 6110, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Melawi"],
            ['kode_kota' => 6111, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Kayong Utara"],
            ['kode_kota' => 6112, 'id_provinsi' => 20, 'nama_kota' => "Kabupaten Kubu Raya"],
            ['kode_kota' => 6171, 'id_provinsi' => 20, 'nama_kota' => "Kota Pontianak"],
            ['kode_kota' => 6172, 'id_provinsi' => 20, 'nama_kota' => "Kota Singkawang"],
            ['kode_kota' => 6201, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Kotawaringin Barat"],
            ['kode_kota' => 6202, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Kotawaringin Timur"],
            ['kode_kota' => 6203, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Kapuas"],
            ['kode_kota' => 6204, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Barito Selatan"],
            ['kode_kota' => 6205, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Barito Utara"],
            ['kode_kota' => 6206, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Sukamara"],
            ['kode_kota' => 6207, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Lamandau"],
            ['kode_kota' => 6208, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Seruyan"],
            ['kode_kota' => 6209, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Katingan"],
            ['kode_kota' => 6210, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Pulang Pisau"],
            ['kode_kota' => 6211, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Gunung Mas"],
            ['kode_kota' => 6212, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Barito Timur"],
            ['kode_kota' => 6213, 'id_provinsi' => 21, 'nama_kota' => "Kabupaten Murung Raya"],
            ['kode_kota' => 6271, 'id_provinsi' => 21, 'nama_kota' => "Kota Palangka Raya"],
            ['kode_kota' => 6301, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Tanah Laut"],
            ['kode_kota' => 6302, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Kota Baru"],
            ['kode_kota' => 6303, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Banjar"],
            ['kode_kota' => 6304, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Barito Kuala"],
            ['kode_kota' => 6305, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Tapin"],
            ['kode_kota' => 6306, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Hulu Sungai Selatan"],
            ['kode_kota' => 6307, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Hulu Sungai Tengah"],
            ['kode_kota' => 6308, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Hulu Sungai Utara"],
            ['kode_kota' => 6309, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Tabalong"],
            ['kode_kota' => 6310, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Tanah Bumbu"],
            ['kode_kota' => 6311, 'id_provinsi' => 22, 'nama_kota' => "Kabupaten Balangan"],
            ['kode_kota' => 6371, 'id_provinsi' => 22, 'nama_kota' => "Kota Banjarmasin"],
            ['kode_kota' => 6372, 'id_provinsi' => 22, 'nama_kota' => "Kota Banjar Baru"],
            ['kode_kota' => 6401, 'id_provinsi' => 23, 'nama_kota' => "Kabupaten Paser"],
            ['kode_kota' => 6402, 'id_provinsi' => 23, 'nama_kota' => "Kabupaten Kutai Barat"],
            ['kode_kota' => 6403, 'id_provinsi' => 23, 'nama_kota' => "Kabupaten Kutai Kartanegara"],
            ['kode_kota' => 6404, 'id_provinsi' => 23, 'nama_kota' => "Kabupaten Kutai Timur"],
            ['kode_kota' => 6405, 'id_provinsi' => 23, 'nama_kota' => "Kabupaten Berau"],
            ['kode_kota' => 6409, 'id_provinsi' => 23, 'nama_kota' => "Kabupaten Penajam Paser Utara"],
            ['kode_kota' => 6411, 'id_provinsi' => 23, 'nama_kota' => "Kabupaten Mahakam Hulu"],
            ['kode_kota' => 6471, 'id_provinsi' => 23, 'nama_kota' => "Kota Balikpapan"],
            ['kode_kota' => 6472, 'id_provinsi' => 23, 'nama_kota' => "Kota Samarinda"],
            ['kode_kota' => 6474, 'id_provinsi' => 23, 'nama_kota' => "Kota Bontang"],
            ['kode_kota' => 6501, 'id_provinsi' => 24, 'nama_kota' => "Kabupaten Malinau"],
            ['kode_kota' => 6502, 'id_provinsi' => 24, 'nama_kota' => "Kabupaten Bulungan"],
            ['kode_kota' => 6503, 'id_provinsi' => 24, 'nama_kota' => "Kabupaten Tana Tidung"],
            ['kode_kota' => 6504, 'id_provinsi' => 24, 'nama_kota' => "Kabupaten Nunukan"],
            ['kode_kota' => 6571, 'id_provinsi' => 24, 'nama_kota' => "Kota Tarakan"],
            ['kode_kota' => 7101, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Bolaang Mongondow"],
            ['kode_kota' => 7102, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Minahasa"],
            ['kode_kota' => 7103, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Kepulauan Sangihe"],
            ['kode_kota' => 7104, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Kepulauan Talaud"],
            ['kode_kota' => 7105, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Minahasa Selatan"],
            ['kode_kota' => 7106, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Minahasa Utara"],
            ['kode_kota' => 7107, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Bolaang Mongondow Utara"],
            ['kode_kota' => 7108, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Siau Tagulandang Biaro"],
            ['kode_kota' => 7109, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Minahasa Tenggara"],
            ['kode_kota' => 7110, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Bolaang Mongondow Selatan"],
            ['kode_kota' => 7111, 'id_provinsi' => 25, 'nama_kota' => "Kabupaten Bolaang Mongondow Timur"],
            ['kode_kota' => 7171, 'id_provinsi' => 25, 'nama_kota' => "Kota Manado"],
            ['kode_kota' => 7172, 'id_provinsi' => 25, 'nama_kota' => "Kota Bitung"],
            ['kode_kota' => 7173, 'id_provinsi' => 25, 'nama_kota' => "Kota Tomohon"],
            ['kode_kota' => 7174, 'id_provinsi' => 25, 'nama_kota' => "Kota Kotamobagu"],
            ['kode_kota' => 7201, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Banggai Kepulauan"],
            ['kode_kota' => 7202, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Banggai"],
            ['kode_kota' => 7203, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Morowali"],
            ['kode_kota' => 7204, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Poso"],
            ['kode_kota' => 7205, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Donggala"],
            ['kode_kota' => 7206, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Toli-Toli"],
            ['kode_kota' => 7207, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Buol"],
            ['kode_kota' => 7208, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Parigi Moutong"],
            ['kode_kota' => 7209, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Tojo Una-Una"],
            ['kode_kota' => 7210, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Sigi"],
            ['kode_kota' => 7211, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Banggai Laut"],
            ['kode_kota' => 7212, 'id_provinsi' => 26, 'nama_kota' => "Kabupaten Morowali Utara"],
            ['kode_kota' => 7271, 'id_provinsi' => 26, 'nama_kota' => "Kota Palu"],
            ['kode_kota' => 7301, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Kepulauan Selayar"],
            ['kode_kota' => 7302, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Bulukumba"],
            ['kode_kota' => 7303, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Bantaeng"],
            ['kode_kota' => 7304, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Jeneponto"],
            ['kode_kota' => 7305, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Takalar"],
            ['kode_kota' => 7306, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Gowa"],
            ['kode_kota' => 7307, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Sinjai"],
            ['kode_kota' => 7308, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Maros"],
            ['kode_kota' => 7309, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Pangkajene Dan Kepulauan"],
            ['kode_kota' => 7310, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Barru"],
            ['kode_kota' => 7311, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Bone"],
            ['kode_kota' => 7312, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Soppeng"],
            ['kode_kota' => 7313, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Wajo"],
            ['kode_kota' => 7314, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Sidenreng Rappang"],
            ['kode_kota' => 7315, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Pinrang"],
            ['kode_kota' => 7316, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Enrekang"],
            ['kode_kota' => 7317, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Luwu"],
            ['kode_kota' => 7318, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Tana Toraja"],
            ['kode_kota' => 7322, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Luwu Utara"],
            ['kode_kota' => 7325, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Luwu Timur"],
            ['kode_kota' => 7326, 'id_provinsi' => 27, 'nama_kota' => "Kabupaten Toraja Utara"],
            ['kode_kota' => 7371, 'id_provinsi' => 27, 'nama_kota' => "Kota Makassar"],
            ['kode_kota' => 7372, 'id_provinsi' => 27, 'nama_kota' => "Kota Parepare"],
            ['kode_kota' => 7373, 'id_provinsi' => 27, 'nama_kota' => "Kota Palopo"],
            ['kode_kota' => 7401, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Buton"],
            ['kode_kota' => 7402, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Muna"],
            ['kode_kota' => 7403, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Konawe"],
            ['kode_kota' => 7404, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Kolaka"],
            ['kode_kota' => 7405, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Konawe Selatan"],
            ['kode_kota' => 7406, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Bombana"],
            ['kode_kota' => 7407, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Wakatobi"],
            ['kode_kota' => 7408, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Kolaka Utara"],
            ['kode_kota' => 7409, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Buton Utara"],
            ['kode_kota' => 7410, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Konawe Utara"],
            ['kode_kota' => 7411, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Kolaka Timur"],
            ['kode_kota' => 7412, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Konawe Kepulauan"],
            ['kode_kota' => 7413, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Muna Barat"],
            ['kode_kota' => 7414, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Buton Tengah"],
            ['kode_kota' => 7415, 'id_provinsi' => 28, 'nama_kota' => "Kabupaten Buton Selatan"],
            ['kode_kota' => 7471, 'id_provinsi' => 28, 'nama_kota' => "Kota Kendari"],
            ['kode_kota' => 7472, 'id_provinsi' => 28, 'nama_kota' => "Kota Baubau"],
            ['kode_kota' => 7501, 'id_provinsi' => 29, 'nama_kota' => "Kabupaten Boalemo"],
            ['kode_kota' => 7502, 'id_provinsi' => 29, 'nama_kota' => "Kabupaten Gorontalo"],
            ['kode_kota' => 7503, 'id_provinsi' => 29, 'nama_kota' => "Kabupaten Pohuwato"],
            ['kode_kota' => 7504, 'id_provinsi' => 29, 'nama_kota' => "Kabupaten Bone Bolango"],
            ['kode_kota' => 7505, 'id_provinsi' => 29, 'nama_kota' => "Kabupaten Gorontalo Utara"],
            ['kode_kota' => 7571, 'id_provinsi' => 29, 'nama_kota' => "Kota Gorontalo"],
            ['kode_kota' => 7601, 'id_provinsi' => 30, 'nama_kota' => "Kabupaten Majene"],
            ['kode_kota' => 7602, 'id_provinsi' => 30, 'nama_kota' => "Kabupaten Polewali Mandar"],
            ['kode_kota' => 7603, 'id_provinsi' => 30, 'nama_kota' => "Kabupaten Mamasa"],
            ['kode_kota' => 7604, 'id_provinsi' => 30, 'nama_kota' => "Kabupaten Mamuju"],
            ['kode_kota' => 7605, 'id_provinsi' => 30, 'nama_kota' => "Kabupaten Mamuju Utara"],
            ['kode_kota' => 7606, 'id_provinsi' => 30, 'nama_kota' => "Kabupaten Mamuju Tengah"],
            ['kode_kota' => 8101, 'id_provinsi' => 31, 'nama_kota' => "Kabupaten Maluku Tenggara Barat"],
            ['kode_kota' => 8102, 'id_provinsi' => 31, 'nama_kota' => "Kabupaten Maluku Tenggara"],
            ['kode_kota' => 8103, 'id_provinsi' => 31, 'nama_kota' => "Kabupaten Maluku Tengah"],
            ['kode_kota' => 8104, 'id_provinsi' => 31, 'nama_kota' => "Kabupaten Buru"],
            ['kode_kota' => 8105, 'id_provinsi' => 31, 'nama_kota' => "Kabupaten Kepulauan Aru"],
            ['kode_kota' => 8106, 'id_provinsi' => 31, 'nama_kota' => "Kabupaten Seram Bagian Barat"],
            ['kode_kota' => 8107, 'id_provinsi' => 31, 'nama_kota' => "Kabupaten Seram Bagian Timur"],
            ['kode_kota' => 8108, 'id_provinsi' => 31, 'nama_kota' => "Kabupaten Maluku Barat Daya"],
            ['kode_kota' => 8109, 'id_provinsi' => 31, 'nama_kota' => "Kabupaten Buru Selatan"],
            ['kode_kota' => 8171, 'id_provinsi' => 31, 'nama_kota' => "Kota Ambon"],
            ['kode_kota' => 8172, 'id_provinsi' => 31, 'nama_kota' => "Kota Tual"],
            ['kode_kota' => 8201, 'id_provinsi' => 32, 'nama_kota' => "Kabupaten Halmahera Barat"],
            ['kode_kota' => 8202, 'id_provinsi' => 32, 'nama_kota' => "Kabupaten Halmahera Tengah"],
            ['kode_kota' => 8203, 'id_provinsi' => 32, 'nama_kota' => "Kabupaten Kepulauan Sula"],
            ['kode_kota' => 8204, 'id_provinsi' => 32, 'nama_kota' => "Kabupaten Halmahera Selatan"],
            ['kode_kota' => 8205, 'id_provinsi' => 32, 'nama_kota' => "Kabupaten Halmahera Utara"],
            ['kode_kota' => 8206, 'id_provinsi' => 32, 'nama_kota' => "Kabupaten Halmahera Timur"],
            ['kode_kota' => 8207, 'id_provinsi' => 32, 'nama_kota' => "Kabupaten Pulau Morotai"],
            ['kode_kota' => 8208, 'id_provinsi' => 32, 'nama_kota' => "Kabupaten Pulau Taliabu"],
            ['kode_kota' => 8271, 'id_provinsi' => 32, 'nama_kota' => "Kota Ternate"],
            ['kode_kota' => 8272, 'id_provinsi' => 32, 'nama_kota' => "Kota Tidore Kepulauan"],
            ['kode_kota' => 9101, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Fakfak"],
            ['kode_kota' => 9102, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Kaimana"],
            ['kode_kota' => 9103, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Teluk Wondama"],
            ['kode_kota' => 9104, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Teluk Bintuni"],
            ['kode_kota' => 9105, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Manokwari"],
            ['kode_kota' => 9106, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Sorong Selatan"],
            ['kode_kota' => 9107, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Sorong"],
            ['kode_kota' => 9108, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Raja Ampat"],
            ['kode_kota' => 9109, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Tambrauw"],
            ['kode_kota' => 9110, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Maybrat"],
            ['kode_kota' => 9111, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Manokwari Selatan"],
            ['kode_kota' => 9112, 'id_provinsi' => 33, 'nama_kota' => "Kabupaten Pegunungan Arfak"],
            ['kode_kota' => 9171, 'id_provinsi' => 33, 'nama_kota' => "Kota Sorong"],
            ['kode_kota' => 9401, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Merauke"],
            ['kode_kota' => 9402, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Jayawijaya"],
            ['kode_kota' => 9403, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Jayapura"],
            ['kode_kota' => 9404, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Nabire"],
            ['kode_kota' => 9408, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Kepulauan Yapen"],
            ['kode_kota' => 9409, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Biak Numfor"],
            ['kode_kota' => 9410, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Paniai"],
            ['kode_kota' => 9411, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Puncak Jaya"],
            ['kode_kota' => 9412, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Mimika"],
            ['kode_kota' => 9413, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Boven Digoel"],
            ['kode_kota' => 9414, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Mappi"],
            ['kode_kota' => 9415, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Asmat"],
            ['kode_kota' => 9416, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Yahukimo"],
            ['kode_kota' => 9417, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Pegunungan Bintang"],
            ['kode_kota' => 9418, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Tolikara"],
            ['kode_kota' => 9419, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Sarmi"],
            ['kode_kota' => 9420, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Keerom"],
            ['kode_kota' => 9426, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Waropen"],
            ['kode_kota' => 9427, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Supiori"],
            ['kode_kota' => 9428, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Mamberamo Raya"],
            ['kode_kota' => 9429, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Nduga"],
            ['kode_kota' => 9430, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Lanny Jaya"],
            ['kode_kota' => 9431, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Mamberamo Tengah"],
            ['kode_kota' => 9432, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Yalimo"],
            ['kode_kota' => 9433, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Puncak"],
            ['kode_kota' => 9434, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Dogiyai"],
            ['kode_kota' => 9435, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Intan Jaya"],
            ['kode_kota' => 9436, 'id_provinsi' => 34, 'nama_kota' => "Kabupaten Deiyai"],
            ['kode_kota' => 9471, 'id_provinsi' => 34, 'nama_kota' => "Kota Jayapura"],

        ];
        DB::table('kotas')->insert($kota);
    }
}
